export const materialesPedidos = [{
    numero: 1,
    pedido: 1,
    estado: 'Pendiente',
    unidades: 1,
    descripcion: 'Portátil Compaq 10T',
    importeUd: 950.00,
    selected: false,
  },
  {
    numero: 2,
    pedido: 1,
    estado: 'Pendiente',
    unidades: 2,
    descripcion: 'Ratón Usb',
    importeUd: 25.00,
    selected: false,
  },
  {
    numero: 3,
    pedido: 1,
    estado: 'Pendiente',
    unidades: 4,
    descripcion: 'Altavoz Multimedia',
    importeUd: 48.00,
    selected: false,
  },
  {
    numero: 4,
    pedido: 2,
    estado: 'Pendiente',
    unidades: 3,
    descripcion: 'Monitor 42"',
    importeUd: 250.00,
    selected: false,
  },
  {
    numero: 5,
    pedido: 2,
    estado: 'Pendiente',
    unidades: 6,
    descripcion: 'Alfombrilla de ratón',
    importeUd: 10.00,
    selected: false,    
  },
  {
    numero: 6,
    pedido: 3,
    estado: 'Pendiente',
    unidades: 2,
    descripcion: 'Mesa escritorio',
    importeUd: 310.00,
    selected: false,
  },
  {
    numero: 7,
    pedido: 3,
    estado: 'Pendiente',
    unidades: 4,
    descripcion: 'Silla Gamer',
    importeUd: 185.00,
    selected: false,
  },
  {
    numero: 8,
    pedido: 3,
    estado: 'Pendiente',
    unidades: 3,
    descripcion: 'Mando Bluetooth',
    importeUd: 32.00,
    selected: false,
  }]